# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Download Tailwind CSS Binary
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.13/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          
      - name: Generate Minified CSS with Tailwind
        run: ./tailwindcss-linux-x64 -i ./static/app.css -o ./static/main.css --minify

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Terser
        run: npm install terser -g

      - name: Minify JavaScript
        run: terser ./static/script.js -o ./static/script.js --compress --mangle
        
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
